format = """
[](#1d2230)\
$os\
$directory\
$git_branch\
$git_status\
[ ](fg:#1d2230)\
$fill\
[](#1d2230)\
$lua\
$python\
$nodejs\
$aws\
$docker_context\
$time\
[ ](fg:#1d2230)\
$line_break\
$character
"""

# $jobs\
# $cmd_duration\
[os]
disabled = false
style = "bg:#1d2230 fg:#ffffff"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[directory]
style = "fg:#458588 bg:#1d2230"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'
